app/controllers/ApplicationController.scala
Quand on validait l'ajout d'agents sans message, il y avait une erreur pas compréhensible par l'utilisateurs.
4 personnes ont eu l'erreurs, je laisse la possibilité de ne pas mettre de message (solution la plus rapide).
On pourra voir pour ajouter un message d'erreur à la place et si on veut forcer l'écriture d'un message.
=> Accepter le message vide pour l'invitation d'agents

app/services/ApplicationService.scala
C'est con, j'ai oublié de les trier, ça marchait avant dans la majorité des cas (j'ai vu un dossier où c'était pas le cas)
=> Correction Bug : Afficher les réponses à une demande dans l'ordre chronologique

app/models/Application.scala
Il y avait un bug : (il y a 0 heures) au lieu de (il y a 3 heures)
=> Fix: affiche les heures correctements

app/actions/LoginAction.scala, app/controllers/AreaController.scala, app/views/allApplication.scala.html, app/views/allUsers.scala.html, app/views/createApplication.scala.html, app/views/editUser.scala.html, app/views/loginHome.scala.html, app/views/main.scala.html, app/views/showApplication.scala.html
- Amélioration des messages indiquant l'adresse email d'Administration+ 
- Suppression du bouton besoins d'aide du menu (c'était ambigu surtout si le mailto ne marche pas)
Avant -> Après
- Pour les admins : changement de territoire avec une liste déroulante (la page territoire continuera à marcher aussi)
- Le reload se fait sur la même page
- Suppression des reférences à la charte et affichage de la validation des CGU : 
- Nouveau message d'erreur quand un lien unique est réutilisé  "Le lien que vous avez utilisé n'est plus valide, il a déjà été utilisé. Si cette erreur se répète, contactez l'équipe Administration+"
- Ajout de détail sur l'export CSV pour les admins
=> Petites Améliorations

app/views/allApplication.scala.html
- Affiche un message si la personne n'a pas de demande et vient d'arriver sur A+
- Si c'est un aidant : 
- Si c'est un agent instructeur et aussi un aidant :
- Si c'est un agent instructeur sans le role aidant :
Pour info, avant c'était comme ça :
=> Page de bienvenue à la première utilisation

data/categories.yaml
Depuis le 1er novembre, la CMU-C et l'ACS ne font plus qu'une : la CSS.
Source : https://www.service-public.fr/particuliers/vosdroits/F10027 .
Cette PR modifie les textes associés dans le mode guidé.
=> Mise à jour CMU-C/ACS en CSS

app/controllers/ApplicationController.scala, app/controllers/AreaController.scala, app/controllers/GroupController.scala, app/controllers/HomeController.scala, app/controllers/UserController.scala, app/models/Answer.scala, app/services/ApplicationService.scala, app/tasks/AutoAddExpertTask.scala, app/views/CSVExport.scala.html, app/views/allApplications.scala.html, app/views/allArea.scala.html, app/views/allEvents.scala.html, app/views/allUsers.scala.html, app/views/createApplication.scala.html, app/views/editGroup.scala.html, app/views/editUser.scala.html, app/views/editUsers.scala.html, app/views/help.scala.html, app/views/importUsers.scala.html, app/views/main.scala.html, app/views/myApplications.scala.html, app/views/reviewUsersImport.scala.html, app/views/showApplication.scala.html, app/views/showCGU.scala.html, app/views/simplifiedCreateApplication.scala.html, app/views/stats.scala.html, public/stylesheets/main.css
> Note : il y a une notion de "territoire en cours" (qui sauvegardé dans le navigateur) qui est perturbant pour les utilisateurs (cause des erreurs aux administrateurs et affiche des vues trompeur). Cette Pull Request supprime en bonne partie cette notion et la laisse qu'au endroit où c'est encore utiliser dans l'application (avant une suppression totale). 
- Suppression du territoire de la réponse (une réponse est embarqué dans la demande)
- Suppression des anciens objets de stockage de réponses
- Suppression d'un maximum de référence du territoire courant
=> Simplification UI Territoire + Nettoyage du territoire courant (currentArea)

app/csv/package.scala, test/csv/CSVSpec.scala
"Nom de la structure labellisable" était pris comme nom de l'utilisateur.
On a vu de supprimer le support de "Nom de la structure labellisable" (ils remplaceront par "Groupe").
On pourra améliorer l'import pour éviter d'utiliser un champs 2 fois.
=> Conflit entre nom d'utilisateur et nom du groupe

app/views/allApplications.scala.html
Les responsables ne devait pas voir le nom du demandeur pour leur stats.
=> Masque le créateur de la demande pour les responsables

app/actions/LoginAction.scala, test/browser/HomeSpec.scala, test/browser/LoginSpec.scala
Si la page demandée est l'index, ne pas requérir d'information d'identification.
=> [416] Ne pas afficher d'erreur d'identification sur la page racine.

.github/workflows/test.yml
- Codacy upload en optionnel
- Lance les tests uniquements sur les pulls requests (sinon il se lance en double)
=> Amélioration Github Actions pour les PR externes

app/views/main.scala.html
=> Corrige affichage du nom et email utilisateur

app/controllers/ApplicationController.scala, app/views/main.scala.html, public/javascripts/main.js, public/stylesheets/main.css, public/stylesheets/mdl-extensions.css
Le footer est mieux placé dans le DOM et ne provoque plus de défauts visuels.
Change le message lorsqu'une application est clôturée.
(note: j'ai changé "cloturée" en "clôturée", ça a l'air d'être l'orthographe correcte)
=> Met les notifications en haut de la page au lieu de l'intérieur de la snackbar.

app/controllers/ApplicationController.scala
Cette fonction est temporaire.
A terme tout le monde devrait pouvoir communiquer avec tous les territoires.
=> Permettre à l'expert d'inviter quelqu'un dans le territoire courant

app/views/allUsersByGroup.scala.html, app/views/editGroup.scala.html
=> Ajoute plus d'espace entre les éléments de la page utilisateurs classique.

app/views/home/page.scala.html, app/views/main.scala.html, public/stylesheets/main.css
Page interne (prod) :
Page interne (demo)
Page externe (prod)
Page externe (demo)
=> Ajoute le header COVID. Corrige le header de demo (s'affiche en prod).

app/controllers/CSVImportController.scala, app/helper/TwirlImports.scala, app/serializers/Anorm.scala, app/services/ApplicationService.scala, app/services/EventService.scala, app/services/UserGroupService.scala, app/services/UserService.scala, app/tasks/RemoveExpiredFilesTask.scala, app/views/showCGU.scala.html, build.sbt
* La liste des warns est plus lisible.
* La liste des warns est calquée sur la liste dans la documentation.
* Supprime le warn "unused import" car il est incompatible avec twirl (même en utilisant sbt-silencer).
=> Ajoute des warns disponible depuis Scala 2.13.

app/helper/EmailHelper.scala, app/services/NotificationService.scala
Fix https://sentry.data.gouv.fr/aplusbetagouvfr/aplus-prod-worldline/issues/1883351/
AddressException
Local address contains control or whitespace
=> Corrige une exception dans les emails avec des noms avec des caractères spéciaux

app/controllers/CSVImportController.scala, app/controllers/GroupController.scala, app/controllers/Operators.scala, app/controllers/UserController.scala, app/serializers/Keys.scala, app/services/EventService.scala
Changement fonctionnels : ajout du paramètre `date` dans `EventService.all` et du query parameter `date` dans `UserController.allEvents`.
J'ai passé `EventService.all` en non bloquant. Ça engendre quelques modifs avec des `Future` un peu partout. Notamment `Operators.scala` a maintenant toutes ses signatures 100% non bloquantes.
=> Ajoute un filtre par date de la liste des events. Service passé en non bloquant.

app/views/showApplication.scala.html
=> Corrige le label d’invitation d’un expert qui ne se voyait pas bien

app/controllers/UserController.scala, app/services/UserService.scala, app/views/editUser.scala.html
Passe `UserService.update` en non-bloquant.
=> Interdit la mise à jour des flags expert et admin via le formulaire utilisateur

.github/workflows/lint.yml, app/controllers/ApplicationController.scala, app/controllers/UserController.scala, app/services/UserService.scala, app/views/editUser.scala.html, app/views/showApplication.scala.html
* Change la date par défaut de début des stats (#705)
* Ajoute un lien vers la fiche utilisateur sur la demande pour les admins (#707)
* Interdit la mise à jour des flags expert et admin via le formulaire. (#708)
* Amélioration de l'Intégration Continue (#703)
=> v0.7.5 - Mise en prod 14/08/2020

app/controllers/ApplicationController.scala, app/controllers/AreaController.scala, app/controllers/UserController.scala, app/services/UserService.scala
* J'ai renommé `UserService.all` => `UserService.allNoNameNoEmail`.
* Créé une autre méthode `UserService.all`
* Supprimé les noms des utilisateurs dans les stats (l'utilité de la méthode n'était pas claire)
=> Ajoute les utilisateurs sans groupe dans les interfaces d'admin

build.sbt
Ça ne marche pas en prod, il n'y a plus de sentry depuis 10 jours.
Note : 
- Vérifier que les changements de version majeur ne pose pas de problème en prod
=> Revert sentry version (doesn't work in prod)

build.sbt, project/plugins.sbt
Suppression de rjs, enlève les erreur bloquantes. A noter qu'il reste des erreurs de polyfills manquants, mais ça ne bloque pas les utilisateurs.
IE11 marche sur windows 7 avec ce fix (formulaire d'inscription CGU + faire des demandes) :
Différence de quelques ko sur le JS legacy :
(avant / prod)
(après / review app)
=> Correction du build pour IE11

.scala-steward.conf
Pour éviter https://github.com/betagouv/aplus/pull/832
=> Pas d'update de sentry-logback par scala-steward

public/stylesheets/main.css
=> Change la couleur grise du texte pour l'accessibilité (point design)

app/models/Application.scala, app/views/myApplications.scala.html, public/stylesheets/main.css, test/models/ApplicationSpec.scala
Afficher les demandes non visualisées en bleu (à la Frontapp)
=> Distinguer les demandes encore non visualisées

app/views/editUser.scala.html, public/stylesheets/main.css
Bonus : rend la partie blanche à droite des checkboxes non clickables.
=> Bouge les checkboxes à droite sur la page utilisateur

app/controllers/CSVImportController.scala, app/controllers/GroupController.scala, app/helper/MiscHelpers.scala, app/helper/TwirlImports.scala, app/models/UserGroup.scala, app/services/UserGroupService.scala, app/views/createApplication.scala.html, app/views/editGroup.scala.html, app/views/helpers/applications.scala, app/views/showApplication.scala.html, conf/evolutions/default/46.sql, public/stylesheets/main.css, test/browser/AnswerSpec.scala, test/browser/ApplicationAccessSpec.scala, test/browser/ApplicationSpec.scala, test/csv/CSVSpec.scala
* Ajout d'un exemple qui montre l'utilité des descriptions
* Fix `group.description` qui avait été supprimé
* Enlève les attributs `style` sur la liste des groupes
* Refactor de la liste des groupes avec scalatags
* ✅ marche sur IE11
=> Ajoute un champ description détaillée pour les groupes

.scala-steward.conf, build.sbt
Passage sur sentry.io (le compte incubateur)
=> Mise à jour sentry à la dernière version pour passage à Sentry.io

.github/workflows/test.yml, .scala-steward.conf, app/controllers/ApplicationController.scala, app/controllers/CSVImportController.scala, app/controllers/GroupController.scala, app/controllers/UserController.scala, app/models/Organisation.scala, app/models/UserGroup.scala, app/services/EventService.scala, app/services/NotificationService.scala, app/services/UserGroupService.scala, app/services/UserService.scala, app/tasks/AutoAddExpertTask.scala, app/views/allUsersNew.scala.html, app/views/editGroup.scala.html, build.sbt, conf/evolutions/default/48.sql, package.json, project/build.properties, project/plugins.sbt
* Répare l’erreur d’export des demandes en CSV (#975)
* Corrige le deprecation warning onFailuresWithBackoff (#982)
* Ajout d'infos manquantes dans les logs (utilisateur et demande) (#987)
* Mise à jour sentry à la dernière version pour passage à Sentry.io (#973)
* Update .scala-steward.conf (#977)
* Ajoute l'organisme Association (#979)
* Ajoute la BAL dans la liste des utilisateurs (#980)
* Les noms de groupes peuvent faire jusqu’à 100 caractères (#981)
* Mise à jour des dépendances (#945) (#955) (#960) (#976) (#969) (#968) (#963) (#959) (#970) (#965) (#978) (#943) (#983)
=> v0.13.5 - Mise en prod 30/03/2021

app/views/home/page.scala.html, public/stylesheets/main.css
=> Ajoute un lien vers betagouv dans le footer et améliore la grosseur et contraste

app/controllers/SignupController.scala, app/models/formModels.scala, app/views/signupAdmin.scala
=> Peut faire un essai avant d’ajouter des préinscriptions

app/controllers/GroupController.scala, app/controllers/UserController.scala, app/models/Authorization.scala, app/models/UserGroup.scala, app/views/allUsersByGroup.scala.html, app/views/editGroup.scala.html, app/views/editMyGroups.scala.html
=> Corrige les groupes non éditables par les responsables

conf/evolutions/default/51.sql
`creator_user_name` est un champ calculé avec la liste de tous les groupes d'un utilisateur qui peuvent dépasser les 200 chars
=> Corrige l’envoi de demande pour certains utilisateurs multigroupes

.scalafmt.conf, app/controllers/ApplicationController.scala, app/controllers/UserController.scala, app/models/Application.scala, app/serializers/ApiModel.scala, app/views/helpers/menuNav.scala.html, app/views/showApplication.scala.html, package.json, project/plugins.sbt, typescript/src/admin.ts, typescript/src/application.ts, typescript/src/applicationAttachment.ts, typescript/src/applicationMandatFields.ts, typescript/src/changeArea.ts, typescript/src/domHelpers.ts, typescript/src/editMyGroups.ts, typescript/src/helpers.ts, typescript/src/mdl-extensions.ts, typescript/src/myApplications.ts, typescript/src/searchInput.ts, typescript/src/showApplication.ts, typescript/src/signup.ts, typescript/src/users.ts, typescript/src/validateAccount.ts, typescript/src/welcome.ts, typescript/tsconfig.json
* Améliore la visibilité de l’icone demande vue et ajoute la date (#1176)
* Ajoute les compile checks en TS (#1161)
* Réduit le nombre de mois de demandes affichés aux admins (#1170)
* Améliore l’erreur de validation du formulaire de réponse (#1171)
* Change l’ordre des colonnes de la liste des utilisateurs (#1172)
* Mise à jour des dépendances (#1164) (#1166) (#1168) (#1167) (#1165) (#1169) (#1173) (#1175) (#1174)
=> v0.16.1 - Mise en prod 21/09/2021

app/helper/Time.scala
=> Corrige l’affichage de l’année des janviers shiftée de +1

app/views/applications/myApplications.scala, app/views/main.scala
Suit les recommandations d'accessibilité https://www.accede-web.com/notices/html-et-css/liens-et-boutons/ne-pas-utiliser-les-attributs-aria-label-et-title-sur-des-liens-ou-boutons-explicites/
=> Supprime les attributs title des liens explicites

app/views/application.scala
=> Ajoute le fait qu’un opérateur a traité la demande

app/actions/LoginAction.scala, app/controllers/ApiController.scala, app/controllers/ApplicationController.scala, app/controllers/SignupController.scala, app/serializers/ApiModel.scala, app/services/DataService.scala, app/services/UserGroupService.scala, app/services/UserService.scala, app/views/publicStats.scala, package.json, typescript/webpack/webpack.common.js
=> Ajoute l’état du déploiement sur la page de stats publique

app/views/editMyGroups.scala
=> Ajoute de l’espace entre le nom et la description du groupe
