app/views/allApplication.scala.html

corrections orthographiques

---

app/views/showApplication.scala.html

Voici les changements du bouton pour plus de clarté. Bonne journée

changement bouton "terminer"

---

app/controllers/UserController.scala
app/models/User.scala
app/services/NotificationService.scala
app/services/UserService.scala
app/views/editUsers.scala.html
conf/evolutions/default/4.sql

- Ajout de délégation de compte (copie des mails et avertissement dans le mail)
- Correction du bug d'edition de membre (Il n'y avait pas de filtrage de zone dans l'édition de membre)
- Ajout d'une date de création des utilisateurs
@TanguyYan @dlequepeys @zohralebel

Délégation de compte

---

app/views/loginHome.scala.html
app/views/main.scala.html

@TanguyYan @dlequepeys @zohralebel  Il n'y a rien à tester avant la mise en production.
J'intégre tout de suite.
Vous recevrais les identifiants en privé sur slack pour voir les stats.

Ajout statistique Piwik

---

app/services/NotificationService.scala
app/views/showApplication.scala.html

Le footer de l'email est clarifié
L'admin peut cloturer une demande

Clarification Email et cloture de demande par un admin

---

app/views/showApplication.scala.html

Amélioration de l'affichage des copier/coller et saut de ligne

---

app/controllers/UserController.scala
app/services/UserService.scala
app/views/allUsers.scala.html
app/views/editUsers.scala.html

- Fix ajout d'utilisateur (ça marchait plus)
- Amélioré sécurité Utilisateurs
- Améliorer affichage utilisateur

Amélioration gestion utilisateurs

---

app/views/showApplication.scala.html
app/views/showCharte.scala.html

Amélioration validation de la charte

---

app/views/allUsers.scala.html
app/views/editUsers.scala.html
build.sbt

Délégation pour tous les navigateurs + amélioration visuels utilisateurs

---

app/controllers/ApplicationController.scala
app/controllers/UserController.scala
conf/messages.fr

Controler taille des champs et afficher une erreur

---

app/controllers/LoginController.scala
app/services/NotificationService.scala

- Nouveau mail:
- Mail automatique de réponse à ne pas répondre:

Email de non réponse + amélioration

---

app/views/editUsers.scala.html
app/views/showApplication.scala.html
public/stylesheets/main.css

Quand on imprime ça devrait rendre ça sous chrome: 
Sous Firefox:

Amélioration impression

---

app/controllers/ApplicationController.scala
app/services/NotificationService.scala
app/views/allApplication.scala.html
app/views/createApplication.scala.html
app/views/main.scala.html
app/views/showApplication.scala.html

- Corriger Bug visibilité des messages (les aidants pouvaient voir les échanges entre agents)
- les agents n'utilisent pas la fonctionnalité d'échange
- Corriger template email (sauf de ligne et italique)
- Ajouts infos pour les administrateurs (créateur et nombre d'invitéà)
- Changer bouton d'aide
- Ajout de boutons d'aide

Fix de bugs, boutons d'aide, ajouts infos admin

---

app/controllers/UserController.scala
app/models/User.scala
app/views/createApplication.scala.html
app/views/main.scala.html
conf/routes
public/javascripts/polyfills.js

Nouvelle selection organisation

---

app/views/allApplication.scala.html
app/views/showApplication.scala.html

- Déplacer Infos de l'usager vers le haut
￼- Date de la demande -> Date
- Mettre en gras les infos Etat, invités, territoires.

Déplacer Infos de l'usager + modification visuels

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/models/Time.scala
app/views/allApplication.scala.html

- Affiche en gras le status "En cours"
- Affiche les dossiers en cours avant les dossiers terminé
Avant -> Après
- Affiche les dates en format plus humain

Améliore l'affichage des dossiers en cours

---

app/controllers/ApplicationController.scala
app/forms/Models.scala
app/views/createApplication.scala.html

- Je complète une nouvelle demande,
- J'ai choisi des organismes
- Je valide
- Il y a une erreur dans le formulaire (titre trop long)
**Avant**
- Les organismes ont été perdu, on doit les recocher
**Après**
- Les organismes coché sont toujours coché

Correction Bug perte d'organisme si formulaire incorrect

---

app/views/showApplication.scala.html
public/stylesheets/main.css

Sous firefox maintenant, ça s'imprime sur plusieurs pages
Je n'ai pas pu tester avec Internet Explorer, il y a des chances que ça marche aussi

Améliore l'impression sous firefox (et peut-être sous IE)

---

.circleci/config.yml
app/controllers/ApplicationController.scala
app/views/allApplication.scala.html
app/views/allApplicationCSV.scala.html
conf/routes

Export CSV

---

app/models/Application.scala
app/views/allApplication.scala.html
app/views/createApplication.scala.html
public/stylesheets/main.css

- @TanguyYan c'est hors tache mais ça devrait aider Zohra et les agents

Filtre sur la liste des demandes (équivalent recherche)

---

app.json
app/controllers/UserController.scala
app/models/Application.scala
app/models/User.scala
app/services/ApplicationService.scala
app/views/allApplication.scala.html
app/views/showApplication.scala.html
conf/evolutions/default/7.sql
conf/routes

- Ajout d'un identifiant séquentiel pour les administrateurs uniquement
- Copie de la base de donnée de demo automatiquement
- Suppression de possibilité de créé des utilisateurs de démo en ligne (remplacé par la fonctionnalité au dessus)

 Ajout id interne pour les administrateurs

---

app.json
app/controllers/UserController.scala
app/models/Application.scala
app/models/User.scala
app/services/ApplicationService.scala
app/views/allApplication.scala.html
app/views/showApplication.scala.html
conf/evolutions/default/7.sql
conf/routes

* Ajout id interne
* Clonage de la base de donnée chez heroku
* Suppression de la création d'utilisateur de démo

Mise en prod 02/01

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/services/ApplicationService.scala
conf/evolutions/default/9.sql

- Si un agent consulte une demande, le status change en "Consultée"
- Un aidant verra le status en "Consultée" si au moins une personne invité a consulté la demande
- Correction de "Clôturé" à "Clôturée"

Visualisation de la consultation des demandes

---

app/models/Application.scala

- Agent: status "Répondu par X" (si même qualité)
- Agents: les couleurs de délais sont supprimé si un agent avec la même qualité à répondu

Ajout de répondu par X si X à la même qualité

---

app/views/showApplication.scala.html

Fix la demande d'utilité sur IE 11

---

app/models/Application.scala
app/services/ApplicationService.scala
app/views/allApplication.scala.html
public/sortable/sortable.css
public/sortable/sortable.js

- Ajout du nom de l'usager dans la liste des demandes
- Ajout d'un bouton détails qui ouvre la demande (et permet d'ouvrir dans un onglet)
Avant -> Après
- Ajout de tri dans l'administration

Ajout Nom dans la liste et liens cliquables pour ouvrir les demandes

---

app/views/createApplication.scala.html
app/views/showApplication.scala.html

Suppression des ombres des tableaux, ajouts d'icone
Avant -> Après
Avant -> Après

Amelioration graphique des formulaires

---

app/views/allApplication.scala.html

Afficher le total de dossier

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/models/Time.scala
app/services/ApplicationService.scala
app/services/UserService.scala
app/views/allApplicationCSV.scala.html
app/views/main.scala.html
app/views/stats.scala.html
build.sbt
conf/routes

Ajout de stats sur les nouvelles demandes (par semaine)
Ajout des stats sur les demandes clôturé (par semaine)

Stats pour les administrateurs

---

public/javascripts/polyfills.js

Bien tester avec des accents et sans accents ( rechercher "piece" doit renvoyer "pièce" )

Corrige la recherche sur internet explorer

---

app/views/allApplicationCSV.scala.html

- Date de clôture
- Non pertinante (Pour les admins uniquement)
- Utile (Pour les admins uniquement)

Ajout nouvelle donnée dans l'export CSV

---

app/views/showApplication.scala.html

- Les messages entre Agents sont maintenant masqué à l'Aidant
- Un message "Ce message n'est pas visible par l'aidant" est affiché aux agents sur ces messages

Corriger la visibilité des messages pour les aidants

---

app/models/Application.scala
app/views/stats.scala.html

(Données de démo)
- Affichage de toutes donnés sur le même graphe
- Tableaux masqué par défaut

Amélioration visibilité stats

---

app/views/showApplication.scala.html
app/views/stats.scala.html

Correction affichage des messages + Ortho stats

---

app/views/stats.scala.html

- Reduction taille des graphes secondaires
- Plus de courbe -> graphe linéaire à la place
- Suppression des demandes clôturés
- Empilage des demandes par utilité (la somme représentent les demandes clôturés)
- Ajout d'une popup qui donne les chiffres aux survols

Correction des graphes

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/models/Time.scala
app/services/ApplicationService.scala
app/services/UserService.scala

Corrige les heures pour les placer à l'heures française

Fix TimeZone

---

app/controllers/ApplicationController.scala
app/models/Answer.scala
app/models/Application.scala
app/services/ApplicationService.scala
app/views/allApplication.scala.html
app/views/showApplication.scala.html
public/stylesheets/main.css

Amélioration de la liste des demandes

---

app/views/showApplication.scala.html

Réponse rapide par l'agent

---

app/controllers/UserController.scala
app/models/User.scala
app/services/UserService.scala
app/views/allUsers.scala.html
app/views/editUsers.scala.html
conf/evolutions/default/14.sql

Ajout Code Commune INSEE

---

app/controllers/ApplicationController.scala
app/controllers/UserController.scala
app/models/Answer.scala
app/models/Application.scala
app/models/User.scala
app/models/UserGroup.scala
app/services/ApplicationService.scala
app/services/UserService.scala
app/views/allUsers.scala.html
app/views/editUser.scala.html
app/views/editUsers.scala.html
app/views/main.scala.html
app/views/stats.scala.html
conf/evolutions/default/15.sql
conf/routes
public/stylesheets/main.css

Groupe d'utilisateurs

---

app/controllers/ApplicationController.scala
app/views/allApplication.scala.html

Toutes les demandes des groupes

---

app/models/Area.scala

Mise en prod 03/04/2019

---

app/controllers/ApplicationController.scala
app/controllers/UserController.scala
app/extentions/Math.scala
app/models/Application.scala
app/models/UserGroup.scala
app/services/UserService.scala
app/views/allUsers.scala.html
app/views/editGroup.scala.html
app/views/helpers/displayUsers.scala.html
app/views/main.scala.html
app/views/showApplication.scala.html
app/views/stats.scala.html
conf/routes

* Add Group edit page
* Add average and median for resolution time + fix satisfaction
* Supprimer une des réponses rapides
* Temps de traitements en jours
* Fix routes
* Ajout courbe demandes créé par territoires
* Ajout courbe demandes créé par territoires
* Fix graphe par administration réceptrice
* Fix graphe par administration réceptrice
* Secure group
* Add change for group admin

Mise en prod 29/04

---

app/models/User.scala

- Ajoute Sylvain comme nouvel Expert A+

Ajoute Sylvain à la liste des experts

---

app/controllers/ApplicationController.scala
app/models/AgeModel.scala
app/models/Answer.scala
app/models/Application.scala
app/models/Area.scala
app/models/Time.scala
app/models/User.scala
app/services/ApplicationService.scala
app/services/EventService.scala
app/tasks/ExpertTask.scala
app/tasks/TasksModule.scala
app/views/allApplication.scala.html
app/views/showApplication.scala.html
conf/application.conf
conf/evolutions/default/18.sql
conf/routes

- Ajout automatique de l'expert après 5 jours si pas de réponse ou 15 jours d'inactivité
- Dans la liste des demandes, toutes les demandes de tous les territoires sont affichés
Avant -> Après
- Correction de bug : quand quelqu'un clique sur "Inviter un expert" le message est visible aux aidants
- Quand un expert a été invité, le bouton "Inviter un expert" disparait
- Dans la liste des demandes pour les admins et responsable, le sujet est déplacé à la fin

Ajout automatique de l'expert après 5 jours si pas de réponse ou 15 jours d'inactivité

---

app/models/User.scala

Suppression des accès de Louis (fin de stage)

Mise à jour utilisateurs

---

.gitignore
app/actions/LoginAction.scala
app/controllers/UserController.scala
app/views/main.scala.html
app/views/showCGU.scala.html
conf/routes
public/html/CGU_13_mai_2019.html

Note :
- Plus besoins du plugin PDF

Affichage de la charte en HTML au lieu de PDF

---

app/actions/LoginAction.scala
app/controllers/AreaController.scala
app/views/allApplication.scala.html
app/views/allArea.scala.html
app/views/allUsers.scala.html
app/views/createApplication.scala.html
app/views/editUser.scala.html
app/views/loginHome.scala.html
app/views/main.scala.html
app/views/showApplication.scala.html

* Ajout aide sur login
* Ajout select pour la zone
* Ajout redirect pour la zone
* Affichage validation CGU
* Amélioration affichage de la demande d'aide
* Changer message CSV
* Amélioration message d'erreur

Mise en prod 5/07 #1

---

app/actions/LoginAction.scala
app/controllers/UserController.scala
app/models/Area.scala
app/models/Event.scala
app/services/EventService.scala
app/views/allApplication.scala.html
app/views/allEvents.scala.html
app/views/main.scala.html
conf/routes
public/javascripts/main.js
public/stylesheets/main.css

- Les admins peuvent voir les logs de l'application (500 derniers par défaut)
Je mets direct en prod, ça me facilite le débogage

Ajout d'un page de log et amélioration des événements

---

app.json
app/actions/LoginAction.scala
app/controllers/ApplicationController.scala
app/controllers/LoginController.scala
app/services/EventService.scala
app/services/NotificationService.scala
app/views/loginHome.scala.html
conf/routes

- Ajout d'une page intermédiaire de validation de connexion :
- Soit l'utilisateur valide en cliquant sur le bouton, sinon c'est validé au bout de 2 secondes
- Permet normalement de contre-balancer le problème de double usage d'un lien
- Supprime le "/32" à la fin des IPs
- Affiche la demande à son créateur si le créateur est admin et expert (cas de Zohra qui créé des demandes)

Amélioration login + petites modifs

---

app.json
app/actions/LoginAction.scala
app/controllers/ApplicationController.scala
app/controllers/LoginController.scala
app/services/EventService.scala
app/services/NotificationService.scala
app/views/loginHome.scala.html
conf/routes

* Affiche l'host uniquement dans l'ip des événements
* Affiche la demande à son créateur s'il est admin
* Page de validation de connexion
* Fix Review App

Mise en prod 08/07 #1

---

app/views/allApplication.scala.html
app/views/main.scala.html
public/stylesheets/main.css
scripts/merge_prod.sh

- Suppression des icones sous Internet Explorer (ne supporte pas les icones)
- Ajout d'un bandeau quand il y a des demandes clôturés
- Ajout d'un bouton "Créer une demande" sur la page toutes les demandes

Améliorations design

---

app/services/NotificationService.scala

- Suppression du tracking d'ouverture
- Remplacement de A+ en Administration+
- Rallongement du texte de l'email de connexion (il était trop court)
- Transformation des email en lien d'envoi d'email

Amélioration du score antispam

---

app/controllers/ApplicationController.scala
app/views/stats.scala.html

- Permet au niveau des stats de choisir si on peut voir les stats du territoire ou de l'ensemble des territoires

Filtrer les stats sur un territoire

---

.circleci/config.yml
app/controllers/HomeController.scala
app/controllers/UserController.scala
app/views/allUsers.scala.html
app/views/createApplication.scala.html
app/views/editGroup.scala.html
app/views/editUser.scala.html
app/views/editUsers.scala.html
app/views/loginHome.scala.html
app/views/showApplication.scala.html
app/views/showCGU.scala.html
app/views/simplifiedCreateApplication.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
test/browser/BaseSpec.scala
test/browser/HomeSpec.scala
test/browser/LoginSpec.scala

- Sécurité : token CSRF 
- Test automatique de la connexion

Ajout token CSRF (Sécurité) + 6 tests automatisés

---

app/actions/LoginAction.scala
app/controllers/LoginController.scala
app/controllers/UserController.scala
app/models/User.scala
app/services/UserService.scala
app/views/allApplication.scala.html
app/views/allArea.scala.html
app/views/allEvents.scala.html
app/views/allUsers.scala.html
app/views/editUser.scala.html
app/views/main.scala.html
app/views/stats.scala.html
conf/evolutions/default/22.sql
public/stylesheets/main.css
test/browser/LoginSpec.scala

- Désactivation d'un utilisateur : 
- Affichage d'un agent désactivé
- Essai de connexion avec un utilisateur désactivé
- Si l'utilisateur été connecté : 
Si un utilisateur est désactivé :
- Il ne peut plus se connecter
- Il ne peut plus faire d'action, il est automatiquement déconnecté

Désactivation d'un utilisateur

---

app/views/editUser.scala.html
app/views/editUsers.scala.html
app/views/stats.scala.html

Changement :
- Correction des stats
- Changement des intitulés pour les utilisateurs de "Nom" à "Nom et prénom"

Correction stats et changement intitulé

---

app/views/editUser.scala.html
app/views/editUsers.scala.html
app/views/stats.scala.html

- Correction stats et changement intitulé (#209)

Mise en prod 02/09/2019 #1

---

app/controllers/ApplicationController.scala
app/controllers/AreaController.scala
app/controllers/UserController.scala
app/services/GroupService.scala
app/services/UserService.scala
app/views/allArea.scala.html
app/views/allUsersNew.scala.html
app/views/editUser.scala.html
app/views/main.scala.html
app/views/simplifiedCreateApplication.scala.html
conf/routes
public/stylesheets/main.css
public/stylesheets/newForm.css

- Ajouts nouvelles pages utilisateurs (en construction)
- Changement de design
- Possibilité d'afficher les utilisateurs de tout un territoire
- Changement design modification d'un utilisateur
- Affichage des groupes dans la liste des territoires

Modification Page utilisateurs

---

app/controllers/UserController.scala
app/models/UserGroup.scala
app/services/GroupService.scala
app/views/allUsers.scala.html
app/views/allUsersNew.scala.html
app/views/editGroup.scala.html
conf/evolutions/default/23.sql

Ajout email du groupe

---

app/controllers/ApplicationController.scala
app/views/allArea.scala.html
app/views/allUsers.scala.html
app/views/createApplication.scala.html
app/views/editUsers.scala.html
app/views/helpers/displayUsers.scala.html
app/views/simplifiedCreateApplication.scala.html
public/stylesheets/newForm.css

Amélioration graphique création de demande

---

app/controllers/ApplicationController.scala
app/views/allArea.scala.html
app/views/allUsers.scala.html
app/views/createApplication.scala.html
app/views/editUsers.scala.html
app/views/helpers/displayUsers.scala.html
app/views/simplifiedCreateApplication.scala.html
public/stylesheets/newForm.css

* Amélioration graphique demande
* Améliorer la sélection des partenaires
* Remplace Administration/Qualité par Qualité
* Affiche l'organisation dans le type de groupe
* Ne pas filtrer les organismes en mode avancé

Mise en Prod 08/10/19 #1

---

app/controllers/UserController.scala
app/services/UserService.scala
app/views/editUser.scala.html
app/views/main.scala.html
conf/routes
public/javascripts/modal.js
public/stylesheets/modal.css

Voir https://trello.com/c/c3tWTaJA/132

Supprimer un utilisateur non utilisé

---

project/plugins.sbt

Revert "Update sbt-codacy-coverage to 1.3.17"

---

app/controllers/ApplicationController.scala
app/services/NotificationService.scala
app/views/allUsers.scala.html
app/views/editGroup.scala.html
app/views/editUser.scala.html
app/views/editUsers.scala.html
app/views/helpers/displayUsers.scala.html
app/views/myApplications.scala.html
app/views/showApplication.scala.html
app/views/stats.scala.html
conf/routes
public/html/CGU_13_mai_2019.html

[199] Modification interaction Administration

---

app/views/showApplication.scala.html

[171] Suppression de "Je ne suis pas disponible"

---

app/views/allUsers.scala.html
app/views/editGroup.scala.html
app/views/editUser.scala.html
public/stylesheets/main.css

[199] Correction taille des descriptions et du fil d'ariane

---

app/services/NotificationService.scala

Fix : rétablissement des notifications pour les personnes invités dans la demande

---

app/controllers/LoginController.scala

Use absolute URL for login request mail.

---

app/views/allArea.scala.html
conf/evolutions/default/29.sql

[265] Nom de groupe unique

---

app/controllers/UserController.scala
app/services/NotificationService.scala
app/views/emails/welcome.scala.html
app/views/help.scala.html
public/stylesheets/main.css

[140] Ajout email de bienvenue + amélioration page d'aide - logs

---

app/controllers/UserController.scala
app/views/editUser.scala.html

- Supprime les "form.get" qui peut lever des exceptions
- Log de suppression d'utilisation et simplification redirection
- Après édition d'un utilisateur, on retourne sur la fiche utilisateur

Rend l'édition utilisateur tolérant aux erreurs

---

app/helper/CsvHelper.scala
app/models/Area.scala
app/views/reviewUsersImport.scala.html

Fix/315 Correction detection de territoires

---

app/views/allApplications.scala.html
app/views/allUsers.scala.html
app/views/main.scala.html

Ils ont été supprimé par la PR #367

Réafficher les codes insee

---

app/controllers/LoginController.scala
app/views/loginHome.scala.html
test/browser/LoginSpec.scala

[325] Amélioration page de login

---

app/views/main.scala.html

[292] Ajout lien CGU dans le bas de page

---

app/controllers/AreaController.scala
app/helper/StringHelper.scala
app/models/Area.scala
app/models/Organisation.scala
app/views/deploymentDashboard.scala.html
app/views/main.scala.html
build.sbt
conf/routes

[320] Tableau de suivi déploiement

---

app/views/emails/welcome.scala.html

Amélioration email d'accueil

---

app/services/EventService.scala
app/views/reviewUsersImport.scala.html

- Affiche toutes les erreurs d'importations en haut de la page
- Améliore le filtre pour l'affichage des logs

Améliore l'affiche des erreurs d'importations + Amelioration filtre log - A review

---

app/controllers/CSVImportController.scala
app/helper/CsvHelper.scala
app/helper/StringHelper.scala
app/models/Area.scala
app/models/Organisation.scala
app/views/editUser.scala.html
app/views/reviewUsersImport.scala.html

v0.2.3 - Mise en prod 03/01/2020 #1

---

app/controllers/ApplicationController.scala
app/views/showApplication.scala.html

[122] Afficher le nom du groupe pour inviter une personne

---

app/views/reviewUsersImport.scala.html
public/stylesheets/main.css

[336] Amélioration PR

---

app/controllers/UserController.scala
app/views/editUser.scala.html

Amélioration Nouvelle UI de saisie territoire/groupe : Code et Sécurité

---

app/controllers/CSVImportController.scala

du coup il y a 2 utilisateurs avec la même adresse email.

[356] les emails sont pas sensible a la casse

---

app/controllers/GroupController.scala
app/controllers/UserController.scala
app/views/allUsersByGroup.scala.html
app/views/allUsersNew.scala.html
app/views/main.scala.html
conf/routes

Nouvelle vue utilisateurs par défaut

---

app/controllers/ApplicationController.scala
app/models/Application.scala
test/browser/ApplicationAccessSpec.scala

- Ajout de tests automatisé en plus du correctif

[431] Bug: Je suis aidant invité mais je ne peux pas voir la demande

---

app/controllers/UserController.scala
app/views/editUsers.scala.html

- Suppression d'aidant dans la vue d'ajout utilisateur
- Ajout de téléphone et responsable
- Les responsables de groupe voit l'ancienne vue utilisateur

[404] Suppression aidant et ajout respo à la création d'utilisateur

---

app/views/deploymentDashboard.scala.html

- Zohra a un bug d'affichage sur le tableau de déploiement, avec une taille fixe, il se peut que ça fonctionne mieux
- J'ai réduit la taille du choix d'option
- J'ai ajouté un bouton download
- J'ai freezé la colonne de département

Ajout sur le tableau de déploiement

---

app/views/main.scala.html

Généralisation du bandeau pour la demo.
Je ne peux pas le mettre le bandeau du framework sur toute la longeur.

[447] Généralisation bandeau demo

---

app/controllers/ApplicationController.scala
app/views/stats.scala.html
build.sbt

S'il y a des simplifications, je suis preneur

Mise en cache des stats

---

app/controllers/ApplicationController.scala
app/controllers/AreaController.scala
app/controllers/CSVImportController.scala
app/controllers/GroupController.scala
app/models/Organisation.scala
app/models/UserGroup.scala
app/serializers/Anorm.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/services/UserGroupService.scala
app/tasks/AutoAddExpertTask.scala
app/views/createApplication.scala.html
app/views/deploymentDashboard.scala.html
app/views/simplifiedCreateApplication.scala.html
test/browser/ApplicationSpec.scala
test/csv/CSVSpec.scala

Ajout d'un type pour l'id des organisations.
Nettoyage de code lié aux organisations.

Change "Maison France Service" par "France Service".

---

app/views/deploymentDashboard.scala.html
build.sbt

Je n'ai pas pu exporter les couleurs, ça ne semble pas possible

Export XLSX du tableau de déploiement

---

app/controllers/ApplicationController.scala
app/models/User.scala
app/views/deploymentDashboard.scala.html
app/views/showApplication.scala.html

- Correction texte dans le tableau de déploiement
- Changer le nom de Zohra
- Mise en cache 1h des stats
- Changement de zone pour l'expert
- Affiche le nom de la structure de l'aidant sur la demande

Résultat Atelier Admin 1 

---

app/views/allArea.scala.html
app/views/editGroup.scala.html

Avant (à gauche) -> Après (à droite)

Correction régression pour la selection d'une organisme pour un groupe

---

app/controllers/ApplicationController.scala
app/services/UserService.scala

Correction du nombre d'utilisateurs qui n'étaient pas filtrés par area.

Tous les membres d'un groupe peuvent voir les stats du groupe

---

app/views/main.scala.html
public/stylesheets/main.css

Ajout d'un label "Se déconnecter" sous le bouton de déconnexion

---

app/models/User.scala
test/browser/AnswerSpec.scala

* cas réponse d'un instructeur
* cas réponse d'un agent
* cas réponse d'un expert invité
* cas expert non invité
* cas agent non invité

Ajout de tests d'intégration pour l'ajout d'une réponse sur une demande

---

.github/workflows/docker.yml
Dockerfile

* Correction image Docker
* Test de construction image docker (#504)

v0.5.1 - Mise en prod 20/02/2020 #2

---

app/controllers/ApplicationController.scala

Corrige la grammaire dans ApplicationController.

---

app/models/Organisation.scala
app/models/UserGroup.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/views/allUsersByGroup.scala.html
app/views/allUsersNew.scala.html
app/views/editGroup.scala.html
app/views/helpers/displayUsers.scala.html
app/views/reviewUsersImport.scala.html

Point Admin 21 février avec Thibaut

---

conf/application.conf

- Sinon ça bloque sur les calls API interne

Autorise les appels API local

---

app/views/main.scala.html
conf/application.conf
public/javascripts/main.js

Attendre #518 et #517 pour merge

v0.5.3 - Mise en prod 24/02/2020

---

app/views/helpers/usersInformations.scala.html
app/views/loginHome.scala.html
app/views/main.scala.html
app/views/showApplication.scala.html
public/stylesheets/main.css
public/stylesheets/mdl-extensions.css

- Passer en blanc les items du menu de gauche afin de les rendre plus visible
- Changer l'icone de mes demandes
- Améliorer icons et placement de l'ajout d'information
- Aligner à gauche les onglets

Point design du 25 février

---

app/views/main.scala.html
public/stylesheets/main.css
public/stylesheets/mdl-extensions.css

Le footer était disposé à la même place en bas correction.
Avant :
Après :

Correction footer fix

---

app/actions/LoginAction.scala
app/controllers/ApiController.scala
app/controllers/ApplicationController.scala
app/controllers/AreaController.scala
app/controllers/GroupController.scala
app/controllers/HomeController.scala
app/controllers/LoginController.scala
app/controllers/UserController.scala
app/forms/MapMapping.scala
app/models/Application.scala
app/models/UserGroup.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/services/ApplicationService.scala
app/services/EventService.scala
app/services/NotificationService.scala
app/services/TokenService.scala
app/services/UserGroupService.scala
app/services/UserService.scala
app/tasks/AutoAddExpertTask.scala
app/views/allUsersByGroup.scala.html
app/views/deploymentDashboard.scala.html
app/views/editUser.scala.html
app/views/franceServiceDeploymentDashboard.scala.html
build.sbt

Ajoute pas mal de warns, dont certains sont des bugs dans l'app actuelle.
Note: il va falloir régler les warns avant, mais il y a les `@deprecated` pour lesquels il faut voir ce qu'on fait.

Ajoute des switches compilateur.

---

app/controllers/ApplicationController.scala
app/controllers/Operators.scala
app/controllers/UserController.scala
app/services/ServicesDependencies.scala
app/services/UserGroupService.scala
conf/application.conf

Création de l'ExecutionContext pour les appels bloquants BDD.
Wrap d'un premier appel dans une Future qui utilise cet ExecutionContext pour commencer le futur travail de migration de tous les appels BDD dans des Futures.

Wrap un premier appel bloquant à la BDD dans une Future.

---

conf/application.conf

Les CGUs étaient bloqué suite à une mise à jour de sécurité.
Cette PR devrait réafficher les CGUs.

Correction bug affichage CGU

---

app/actions/LoginAction.scala
app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/controllers/HomeController.scala
app/controllers/LoginController.scala
app/models/LoginToken.scala
app/models/User.scala
app/services/EventService.scala
app/services/ServicesDependencies.scala
app/tasks/AutoAddExpertTask.scala
app/views/allEvents.scala.html
app/views/createApplication.scala.html
app/views/helpers/changeArea.scala.html
app/views/main.scala.html
app/views/showApplication.scala.html
app/views/simplifiedCreateApplication.scala.html
test/browser/LoginSpec.scala

- Nettoyage du code
- Changement d'emplacement du selecteur de territoire sur la création de demande 
- Et pour l'expert uniquement : 
- Ça garde le territoire en cookie
- Affichage du territoire dans la demande
- Suppression du "Besoin d'aide ? Contactez-nous sur" des pages création de demande (il est déjà présent dans la page )

Supprimer des warnings

---

app/views/createApplication.scala.html
app/views/simplifiedCreateApplication.scala.html

Ajoute un feedback sur la création de demande lorsque un champ obligatoire est vide

---

app/views/main.scala.html
public/stylesheets/main.css

Changer lien Webinaire en FAQ

---

app/views/createApplication.scala.html
app/views/helpers/usersInformations.scala.html
app/views/simplifiedCreateApplication.scala.html

Ajout de label et astérisques sur les champ obligatoires de création de demande

---

app/views/createApplication.scala.html
app/views/helpers/usersInformations.scala.html
app/views/simplifiedCreateApplication.scala.html

Ajoute un astérisque manquant sur un champ obligatoire

---

app/views/allApplications.scala.html
app/views/editGroup.scala.html
app/views/editUsers.scala.html
public/stylesheets/main.css

Améliore la vue des demandes pour les responsables.

---

app/views/helpers/menuNav.scala.html
app/views/main.scala.html
public/stylesheets/main.css

Les liens du menu restent dans une position appuyée lorsque l'on est sur la page pointée

---

app/controllers/CSVImportController.scala
app/models/formModels.scala
app/views/reviewUsersImport.scala.html

En terme de front, il n'y a qu'une icône de warning pour l'instant.

Permet d'importer des utilisateurs dans plusieurs groupes

---

app/views/home/page.scala.html
app/views/main.scala.html
public/javascripts/main-page-bottom.js
public/javascripts/main.js

- Affichage du bandeau démo sur la nouvelle vue vue home
- Correction régression qui n'affichait plus le bandeau sur les autres pages

Correction bandeau demonstration

---

app/views/main.scala.html
public/stylesheets/main.css

Corrige notamment : https://github.com/betagouv/aplus/pull/579#issuecomment-612086969

Place les éléments précédemment centrés en haut de la page (toutes les demandes)

---

app/controllers/ApplicationController.scala
app/controllers/HomeController.scala
app/controllers/LoginController.scala
app/controllers/UserController.scala
app/models/EventType.scala
app/views/allUsersByGroup.scala.html
app/views/editGroup.scala.html
app/views/emails/notificationBAL.scala.html
app/views/helpers/usersInformations.scala.html
app/views/home/connectionFormPanel.scala.html
app/views/home/page.scala.html
app/views/home/sendbackEmailForm.scala.html
app/views/loginHome.scala.html
app/views/main.scala.html
app/views/showCGU.scala.html
app/views/welcome.scala.html
build.sbt
conf/routes
project/plugins.sbt
public/javascripts/main-page-bottom.js
public/javascripts/main.js
public/stylesheets/main.css

* Ajoute le bandeau COVID. (#602)
* Ajoute une page d'accueil, qui apparaît après avoir validé les CGU. (#551)
* Ajoute plus d'espace entre les éléments de la page utilisateurs classique. (#596)
* Correction bandeau demonstration (ne s'affichait plus). (#586)
* Corrige des coquilles dans l'email de notification. (#600)
* Corrections graphiques. (#601)

v0.6.4 - Mise en prod 15/04/2020

---

app/controllers/ApplicationController.scala
app/views/createApplication.scala.html
app/views/simplifiedCreateApplication.scala.html
public/javascripts/main-page-bottom.js
public/stylesheets/main.css
public/stylesheets/mdl-extensions.css

Ajoute des filtres par catégorie sur la page de demande

---

app/views/reviewUsersImport.scala.html

J'ouvre la PR, la modif est faite par @Aurelie-J

Reformulation texte pour une meilleure compréhension

---

app/views/editUsers.scala.html

J'ouvre la PR, la modif est faite par @Aurelie-J

Reformulation pour améliorer la compréhension

---

app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/helper/TwirlImports.scala
app/models/Application.scala
app/models/Area.scala
app/models/formModels.scala
app/serializers/Anorm.scala
app/serializers/DataModel.scala
app/services/ApplicationService.scala
app/services/EventService.scala
app/services/UserGroupService.scala
app/services/UserService.scala
app/tasks/RemoveExpiredFilesTask.scala
app/views/createApplication.scala.html
app/views/editUsers.scala.html
app/views/reviewUsersImport.scala.html
app/views/showApplication.scala.html
app/views/showCGU.scala.html
app/views/simplifiedCreateApplication.scala.html
build.sbt
conf/evolutions/default/36.sql
project/build.properties
public/javascripts/main-page-bottom.js
public/stylesheets/main.css
public/stylesheets/mdl-extensions.css
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/csv/CSVSpec.scala

* Ajoute des filtres par catégorie sur la page de demande (#597)
* Ajoute le type de mandat et le lien d'aide dans les conditions du COVID19 (#591)
* Amélioration de texte

v0.6.5 - Mise en prod 30/04/2020

---

app/views/createApplication.scala.html
app/views/helpers/usersInformations.scala.html
app/views/showApplication.scala.html
public/javascripts/main-page-bottom.js
public/stylesheets/main.css
public/stylesheets/mdl-extensions.css

Améliore graphiquement la réponse à une demande.

---

.github/workflows/dockerpublish.yml

Publication automatique de la prod sur le repository github docker

Github docker packages

---

app/views/home/page.scala.html
app/views/main.scala.html

Change le message du header COVID19

---

app/actions/LoginAction.scala
app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/controllers/Operators.scala
app/controllers/UserController.scala
app/helper/MDLForms.scala
app/helper/PlayFormHelper.scala
app/helper/StringHelper.scala
app/helper/Time.scala
app/models/Error.scala
app/models/EventType.scala
app/services/ApplicationService.scala
app/services/EventService.scala
app/tasks/AutoAddExpertTask.scala
app/views/helpers/usersInformations.scala.html
app/views/helpers/usersInformationsDynamicForm.scala.html
app/views/helpers/usersInformationsInput.scala.html
conf/application.conf
public/stylesheets/main.css
public/stylesheets/mdl-extensions.css

Améliorations faites dans #620 mais qui ne concernent pas le Mandat :
* `userInformationsInput`est coupé en 2 parties : champs obligatoires et champs optionels
* Ajout de fonctions de normalizations d'input string
* Meilleur nommage et ajout de l'exception dans `EventService`
* Type `Error` amélioré avec plus d'infos
* Ajout de `autoApplyDowns` via env variable dans les évolutions Play

Améliorations diverses

---

app/views/home/page.scala.html
app/views/main.scala.html

Nouveau texte bandeau : Dans le contexte de la loi d'état d'urgence sanitaire (avril 2021), Administration+ s'efforce de faciliter la résolution des blocages administratifs en mettant à votre disposition un système de mandat à distance.

Mise à jour du texte du bandeau

---

app/views/createApplication.scala.html
app/views/helpers/usersInformations.scala.html

Pas vraiment un point "admin", mais des modifs pour présenter Administration+ et le mandat SMS
* Ajout d’un titre pour le bas du formulaire de demande
* Déplace le formulaire de mandat SMS en bas de la page de demande

Point Admin 2020 06 15

---

app/controllers/AreaController.scala
app/models/Organisation.scala

* Déduplique la liste des organismes dans `AreaController`

Ajoute l'organisme MSD (Maisons des solidarités départementales)

---

app/views/editUsers.scala.html

Reduit la taille des champs sur la vue d'ajout d'utilisateurs

---

app/controllers/ApplicationController.scala
app/serializers/Keys.scala
app/views/allApplications.scala.html

Ajoute un filtre de demandes ouvertes sur la page admin des demandes

---

.github/workflows/lint.yml
.gitignore
app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/controllers/GroupController.scala
app/controllers/Operators.scala
app/controllers/UserController.scala
app/serializers/Keys.scala
app/services/EventService.scala
app/views/allApplications.scala.html
app/views/showApplication.scala.html
build.sbt

* Ajoute un filtre de demandes ouvertes sur la page admin des demandes (#664)
* Ajoute un filtre par date sur la liste des évènements (#663)
* Corrige le label d’invitation d’un expert qui ne se voyait pas bien (#670) 
* Amélioration de l'intégration continue (#667)

v0.7.1 - Mise en prod 21/07/2020

---

app.json
app/services/NotificationService.scala
conf/application.conf

Fait fonctionner les urls pour les apps de review

---

app/helper/TwirlImports.scala
app/views/helpers/applications.scala
app/views/myApplications.scala.html
public/stylesheets/main.css

Nouvelle et Consultée :
Clôturée :
Envoyée :
Répondu :

Met une couleur de fond sur le label du status d’une demande

---

.github/workflows/test.yml
app/controllers/ApplicationController.scala
app/helper/TwirlImports.scala
app/models/Organisation.scala
app/models/User.scala
app/services/SmsService.scala
app/services/UserService.scala
app/tasks/AutoAddExpertTask.scala
app/views/createApplication.scala.html
app/views/helpers/applications.scala
app/views/myApplications.scala.html
build.sbt
package.json
public/stylesheets/main.css
typescript/webpack/webpack.dev.js
typescript/webpack/webpack.prod.js

- Met une couleur de fond sur le label du status d’une demande (#686)
- Ajoute un job de CI qui vérifie que le frontend compile (#683) 
- Supprime Thibault (#695) 
Correction de bugs :
- Affiche le nom des structures MSAP dans le mandat SMS (#681) 
- Corrige la liste d’experts dans le cas où ils sont en BDD (#697) 
- Corrige une coquille sur la page demande (#696)

v0.7.3 - Mise en prod 04/08/2020

---

app/models/EventType.scala
app/services/ApplicationService.scala
app/services/NotificationService.scala
app/services/ServicesDependencies.scala
app/services/UserService.scala
app/tasks/WeeklyEmailsModule.scala
app/tasks/WeeklyEmailsTask.scala
conf/application.conf

Point technique : j'ai wrap `sendMail` pour qu'il soit non bloquant. Voir si ça marche bien, et on pourra utiliser la version non bloquante après.

Ajoute les emails hebdomadaires (relance des demandes non clôturées)

---

app/models/EventType.scala
app/services/ApplicationService.scala
app/services/NotificationService.scala
app/services/ServicesDependencies.scala
app/services/UserService.scala
app/tasks/WeeklyEmailsModule.scala
app/tasks/WeeklyEmailsTask.scala
build.sbt
conf/application.conf
package.json
project/plugins.sbt

* Ajoute les emails hebdomadaires (relance des demandes non clôturées) (#689)
* Mise à jour des dépendances (#701) (#698) (#700)

v0.7.4 - Mise en prod 11/08/2020

---

.github/workflows/lint.yml

Pour checker les PR sur les code formatters

Ajoute le lint sur les PRs

---

app/views/showApplication.scala.html

Ajoute un lien vers la fiche utilisateur sur la demande pour les admins

---

app/services/NotificationService.scala

* Le seul changement fonctionnel est une ligne en bas du footer concernant IE
* Scalatag-ify les 2 emails qui ont un footer
* Ajoute le footer aux 2 emails concernant les SMS

Ajoute un warning concernant IE dans le footer des emails.

---

app/controllers/ApplicationController.scala
app/helper/MDLForms.scala
app/models/formModels.scala
app/views/createApplication.scala.html
app/views/helpers/usersInformations.scala.html
app/views/helpers/usersInformationsDynamicForm.scala.html
app/views/showApplication.scala.html
public/javascripts/main-page-bottom.js
test/browser/ApplicationSpec.scala

* Supprime Prénom, Nom, Date de naissance des champs de la réponse

Corrige les champs optionnels qui devenaient obligatoires

---

app/views/myApplications.scala.html

Ajoute l’id interne des demandes sur la page mes demande pour les admins

---

app/controllers/ApplicationController.scala
app/controllers/AreaController.scala
app/controllers/UserController.scala
app/helper/MDLForms.scala
app/models/formModels.scala
app/services/NotificationService.scala
app/services/UserService.scala
app/views/createApplication.scala.html
app/views/helpers/usersInformations.scala.html
app/views/helpers/usersInformationsDynamicForm.scala.html
app/views/myApplications.scala.html
app/views/showApplication.scala.html
build.sbt
conf/evolutions/default/38.sql
conf/evolutions/default/39.sql
package.json
public/javascripts/main-page-bottom.js
test/browser/ApplicationSpec.scala

* Ajoute un warning concernant IE dans le footer des emails. (#688)
* Ajoute l’id interne des demandes sur la page mes demandes pour les admins (#718)
* Ajoute des views en BDD qui ne contiennent que la metadata (#716)
* Mise à jour des dépendances (#711) (#712) (#713) (#714)
* Interdit les duplicats d'emails en minuscules (#665)
* Corrige les champs optionnels qui devenaient obligatoires (#710)
* Ajoute les utilisateurs sans groupe dans les interfaces d'admin (#706)
* Corrige les groupes ne contenant que des utilisateurs désactivés visibles sur la demande (#673)

v0.8.0 - Mise en prod 25/08/2020

---

app/views/allUsersNew.scala.html

Ajoute la colonne “compte partagé” sur la page utilisateurs

---

app/views/createApplication.scala.html
app/views/showApplication.scala.html

Ajoute l’étoile rouge pour la signature sur les comptes partagés

---

app/controllers/ApplicationController.scala
app/controllers/GroupController.scala
app/controllers/UserController.scala
app/services/UserService.scala

Les utilisateurs désactivés ne sont plus retournés par défaut (par groupe ids)

---

app/views/franceServiceDeploymentDashboard.scala.html
package.json
typescript/src/admin.ts
typescript/src/global.d.ts
typescript/src/index.ts

(admin.js était uniquement utilisé sur la page déploiement FS)

Change le fichier admin.js en admin.ts (avec les modifs pour compiler)

---

app/services/NotificationService.scala
app/views/showApplication.scala.html

"Clore la demande" => "Clore l'échange"

Reformule le bouton de clôture de demande

---

app/controllers/ApplicationController.scala
app/models/formModels.scala
app/views/showApplication.scala.html
public/stylesheets/main.css

Ajout de l’invitation par groupes d’instructeurs sur les demandes

---

app/models/Authorization.scala

On peut le faire directement dans la gestion de droit, c'est top !

Enlever tous les droits aux personnes désactivés

---

.scalafmt.conf
app/controllers/ApiController.scala
app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/controllers/UserController.scala
app/forms/MapMapping.scala
app/helper/MessageBirdApi.scala
app/helper/OvhApi.scala
app/helper/PlayFormHelper.scala
app/models/Application.scala
app/models/Authorization.scala
app/models/formModels.scala
app/serializers/Anorm.scala
app/serializers/JsonFormats.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/services/ApplicationService.scala
app/services/AttachmentService.scala
app/services/NotificationService.scala
app/services/SmsApi.scala
app/services/SmsService.scala
app/views/showApplication.scala.html
app/views/stats/StatsData.scala
build.sbt
package.json
public/stylesheets/main.css
test/browser/AnswerSpec.scala
test/browser/LoginSpec.scala

* Raccourcit la taille du mandat SMS (#735) 
* Reformule le bouton de clôture de demande (#737)
* Ajout de l’invitation par groupes d’instructeurs sur les demandes (#736)
* Enlève tous les droits aux personnes désactivées (#739) 
* Mise à jour des dépendances et migrations (#730) (#740) (#746) (#744) (#745) (#747)

v0.9.0 - Mise en prod 22/09/2020

---

Dockerfile
azure-task.yaml

* Ajoute un fichier YAML pour le build Docker sur ACR (Azure) [doc](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-multistep-task) et [référence](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml)
* Le build Scala du Dockerfile est fait dans une image de build et j'ai ajouté NodeJS pour accélérer la compilation des assets (26min => 7min)

Ajoute une task Azure et optimise un peu le Dockerfile

---

Dockerfile

* Upgrade image de base openjdk:8u242 => openjdk:8u265
* Supprime le double téléchargement de scala et sbt

Corrige le Dockerfile, le dossier data était manquant

---

app/controllers/LoginController.scala
app/controllers/UserController.scala
test/browser/LoginSpec.scala

* Reformulation du message d’erreur lorsque l'email n'existe pas
* Correction d’une faute d’orthographe dans le message d’erreur d’ajout

Corrections de fautes d'orthographe et reformulations

---

app/controllers/LoginController.scala
app/helper/Time.scala
app/models/User.scala
app/services/NotificationService.scala
app/views/emails/WeeklyEmailInfos.scala
app/views/emails/common.scala
app/views/home/connectionFormPanel.scala.html
app/views/home/emailSentFeedbackPanel.scala.html
app/views/magicLinkAntiConsumptionPage.scala.html

Améliore les formulations dans les étapes du lien magique

---

app/helper/Time.scala
app/views/createApplication.scala.html

Ajoute un exemple de date et heure dans la demande

---

app/views/createApplication.scala.html
app/views/helpers/usersInformationsInput.scala.html
app/views/showApplication.scala.html
public/stylesheets/main.css

Améliorations UI suite au point design

---

app/controllers/ApplicationController.scala

@niladic J'ai repris les refactoring que tu avais acceptés dans une autre PR précédente

Quelques refactoring de la classe ApplicationController

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/views/emails/common.scala
app/views/helpers/applications.scala
app/views/myApplications.scala.html
app/views/showApplication.scala.html
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/browser/HomeSpec.scala
test/models/ApplicationSpec.scala

Story faite dans le cadre de l'objectif : Explorer et trouver des solutions simples à "pourquoi les répondues ne sont pas clôturées"
https://trello.com/c/hAM1nfO7

Wording : renommer "clôturer" par "archiver"

---

app/controllers/Operators.scala
app/models/Application.scala
app/serializers/DataModel.scala
app/services/ApplicationService.scala
app/views/myApplications.scala.html
conf/evolutions/default/42.sql
public/stylesheets/main.css
test/models/ApplicationSpec.scala

Les demandes avec des nouvelles réponses ont un badge de notifications

---

app/views/emails/common.scala

Insérer un espace entre les liens et le message dans le template de mail de bienvenue

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/models/EventType.scala
app/services/ApplicationService.scala
app/views/showApplication.scala.html
conf/routes

Le bouton "réouvrir l'échange" apparait sur les demandes archivées, pour les personnes autorisées à clôturer les demandes :

Les demandes peuvent être réouvertes

---

app/views/emails/welcome.scala.html

ajout de l'accès à  : 
- la documentation d'A+,
- la vidéo de démarrage rapide (focus dessus),
- la page d'inscription aux prochaines formations

Ajoute des informations dans l'email de bienvenue

---

app/controllers/ApplicationController.scala
app/helper/StringHelper.scala
app/models/Answer.scala
app/models/Application.scala
app/models/formModels.scala
app/serializers/DataModel.scala
app/services/ApplicationService.scala
app/tasks/AutoAddExpertTask.scala
app/views/helpers/applications.scala
app/views/showApplication.scala.html
test/models/ApplicationSpec.scala

Ajout de la réponse rapide "traitée" pour l'instructeur
Ajout du tag traité dans le cas où le dernier message contient le texte de la réponse "traitée"
Ajout d'une invitation à archiver pour l'aidant lorsque l'instructeur choisi la réponse rapide :

Ajouter une réponse "j'ai traité la demande" rapide pour l'instructeur

---

app/serializers/DataModel.scala
azure-task.yaml

* Tâches ops (#850)
* Corrige mauvaise case dans le json Format (#851)

v0.11.1 - Mise en prod 17/11/2020 - fix

---

app/views/emails/common.scala

Met en gras l’heure limite du lien magique

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/services/ApplicationService.scala
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/models/ApplicationSpec.scala

Basé sur https://github.com/betagouv/aplus/pull/820

Utilise les groupes invités pour les stats

---

app/views/editUser.scala.html

Afficher les groupes d'un utilisateur avec un lien vers d'édition (le titre n'affiche que le headOption)

---

app/serializers/DataModel.scala
app/services/NotificationService.scala

Basé sur https://github.com/betagouv/aplus/pull/820

Corrige les emails de groupe

---

app/views/showApplication.scala.html
public/stylesheets/main.css

Réduire la taille des blocs de réponses (point design) 

---

.scalafix.conf
app/helper/StringHelper.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/views/emails/common.scala
build.sbt
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/browser/LoginSpec.scala

Formalisation de https://github.com/betagouv/aplus/pull/873

Ajoute les règles scalafix de cats

---

.scalafix.conf
app/controllers/ApplicationController.scala
app/controllers/UserController.scala
app/helper/StringHelper.scala
app/helper/Time.scala
app/models/User.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/services/UserGroupService.scala
app/views/emails/common.scala
app/views/showApplication.scala.html
app/views/stats/StatsData.scala
build.sbt
package.json
project/plugins.sbt
public/stylesheets/main.css
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/browser/LoginSpec.scala
test/csv/CSVSpec.scala

* Optimise 2 méthodes lentes dans le rendu des stats (#864)
* Améliorations graphiques (#869) (#870)
* Amélioration du code (#873) (#881)
* Mise à jour des dépendances (#872) (#877) (#875) (#879) (#882)
*  Corrige les stats de groupes (#880)

v0.12.1 - Mise en prod 2/12/2020

---

app/controllers/ApplicationController.scala
app/models/Application.scala
app/views/helpers/applications.scala
app/views/myApplications.scala.html
app/views/stats/StatsData.scala
package.json
public/stylesheets/main.css
test/models/ApplicationSpec.scala

Les nouveaux status sont : 
"Archivée"
"Traitée" / "À archiver"
"En cours"
"Nouvelle" / "Envoyée"

Mettre à jour long status

---

app/controllers/UserController.scala
app/models/formModels.scala

Suppression contrainte téléphone dans "mon profil"

---

app/controllers/UserController.scala
app/models/EventType.scala
app/models/User.scala
app/models/formModels.scala
app/services/UserService.scala
app/views/editMyGroups.scala.html
app/views/helpers/menuNav.scala.html
app/views/main.scala.html
build.sbt
conf/routes
public/stylesheets/main.css

1. On ne peut pas se supprimer soi-même (la restriction est seulement côté front) => garde fou pour éviter les groupes vides
2. On ne peut pas supprimer un utilisateur qui n'est pas de son groupe
3. On ne peut pas ajouter un utilisateur dans un groupe dans lequel on n'est pas déjà présent
4. On ne peut pas ajouter un utilisateur qui n'est pas déjà utilisateur d'Administration+
5. Pas de contrainte sur les territoires
Vue initiale :
Cas d'erreur : l'utilisateur n'existe pas dans A+ :
Cas d'erreur : l'utilisateur existe déjà dans le groupe :
Cas d'erreur : l'adresse email n'est pas renseignée :
Après review design avec @Aurelie-J :

L'utilisateur peut ajouter et supprimer des membres de ses groupes

---

.github/workflows/test.yml
.scala-steward.conf
app/controllers/ApplicationController.scala
app/controllers/GroupController.scala
app/controllers/UserController.scala
app/models/Application.scala
app/models/Authorization.scala
app/models/EventType.scala
app/models/User.scala
app/models/UserGroup.scala
app/models/formModels.scala
app/services/UserService.scala
app/views/editMyGroups.scala.html
app/views/helpers/applications.scala
app/views/helpers/menuNav.scala.html
app/views/main.scala.html
app/views/myApplications.scala.html
app/views/showApplication.scala.html
app/views/stats/StatsData.scala
build.sbt
conf/evolutions/default/45.sql
conf/routes
package.json
project/build.properties
project/plugins.sbt
public/stylesheets/main.css
test/models/ApplicationSpec.scala
test/models/AuthorizationSpec.scala

* Mettre à jour long status (#874)
* L'utilisateur peut ajouter et supprimer des membres de ses groupes (#876)
* Corrige PG qui explose sur les stats (#887)
* Correction du bug sur l'affichage des fichiers dans les demandes et les réponses (#888)
* Suppression de la contrainte téléphone dans "mon profil" (#891)
* Améliore les logs de l’ajout de groupe (#905)
* Ajoute un index sur la table event pour les stats (#906)
* Mise à jour des dépendances (#886) (#883) (#897) (#896) (#893) (#892) (#895) (#898) (#894) (#899) (#900) (#901) (#903)

v0.13.0 - Mise en prod 21/12/2020

---

app/views/editUser.scala.html
package.json
project/build.properties
public/stylesheets/main.css

* Bouge les checkboxes à droite sur la page utilisateur (#911)
* Mise à jour des dépendances (#907) (#908) (#909)

v0.13.1 - Mise en prod 29/12/2020

---

app/controllers/CSVImportController.scala
app/models/formModels.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/views/reviewUsersImport.scala.html
test/csv/CSVSpec.scala

Pour préparer le refacto des forms utilisant `User`.

Renomme UserFormData en CSVUserFormData

---

app/controllers/ApplicationController.scala
app/serializers/Keys.scala
app/services/ApplicationService.scala
app/views/helpers/menuNav.scala.html

défaut 12, pour l'export 24, query param "nombreDeMoisAffiche"

Ajoute une limite par défaut sur le nombre de demandes admin

---

app/controllers/CSVImportController.scala
app/controllers/GroupController.scala
app/controllers/UserController.scala
app/helper/StringHelper.scala
app/helper/Time.scala
app/models/User.scala
app/models/UserGroup.scala
app/services/UserService.scala

Ajoute les infos utilisateur et groupe dans les logs

---

app/controllers/CSVImportController.scala
app/controllers/GroupController.scala
app/controllers/UserController.scala
app/models/User.scala
app/models/UserGroup.scala
app/models/formModels.scala
app/services/UserGroupService.scala
app/services/UserService.scala
app/views/editGroup.scala.html
app/views/editUser.scala.html
conf/evolutions/default/47.sql
public/stylesheets/main.css
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/browser/LoginSpec.scala
test/csv/CSVSpec.scala

Ajoute un champ de commentaire pour le support (utilisateur et groupe)

---

app/controllers/CSVImportController.scala
app/controllers/GroupController.scala
app/controllers/UserController.scala
app/helper/MiscHelpers.scala
app/helper/StringHelper.scala
app/helper/Time.scala
app/helper/TwirlImports.scala
app/models/User.scala
app/models/UserGroup.scala
app/models/formModels.scala
app/services/UserGroupService.scala
app/services/UserService.scala
app/views/createApplication.scala.html
app/views/editGroup.scala.html
app/views/editUser.scala.html
app/views/helpers/applications.scala
app/views/showApplication.scala.html
build.sbt
conf/evolutions/default/46.sql
conf/evolutions/default/47.sql
public/stylesheets/main.css
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/browser/LoginSpec.scala
test/csv/CSVSpec.scala

* Ajoute un champ description détaillée pour les groupes (#937)
* Ajoute un champ de commentaire pour le support (utilisateur et groupe) (#938)
* Ajoute les infos utilisateur et groupe dans les logs (#931)
* Mise à jour des dépendances (#924) (#934)

v0.13.3 - Mise en prod 26/01/2021

---

app/views/helpers/csv.scala
app/views/reviewUsersImport.scala.html

Ajoute des liens de navigation entre erreurs et groupes sur l'import CSV

---

app/views/emails/welcome.scala.html
app/views/help.scala.html
app/views/helpers/csv.scala
app/views/home/page.scala.html
app/views/magicLinkAntiConsumptionPage.scala.html
app/views/main.scala.html
app/views/reviewUsersImport.scala.html
build.sbt
package.json
project/build.properties

*  Ajoute des liens de navigation entre erreurs et groupes sur l'import CSV (#953)
* Supprimer le numéro d'appel (#954)
* Mise à jour des dépendances (#933) (#940) (#941) (#947) (#952)

v0.13.4 - Mise en prod 22/02/2021

---

build.sbt

Update vers scala 2.13.5

---

app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/controllers/UserController.scala
app/services/EventService.scala
app/tasks/AutoAddExpertTask.scala

Simplification de EventService

Ajout d'infos manquantes dans les logs (utilisateur et demande)

---

app/controllers/ApplicationController.scala
app/models/EventType.scala

Erreurs de validation dans le formulaire d’invitation passées de error en warn.

Corrige les opérateurs non instructeurs invités sur les demandes

---

app/controllers/JavascriptController.scala
app/views/allUsersNew.scala.html

Ajoute des liens vers les groupes sur la page utilisateurs

---

app/controllers/UserController.scala
app/models/Authorization.scala
app/views/editMyGroups.scala.html

Ajoute des liens vers le groupe ou l’utilisateur sur la page groupes

---

app/controllers/JavascriptController.scala
app/views/editUser.scala.html
app/views/helpers/head.scala
app/views/home/page.scala.html
app/views/main.scala.html
build.sbt
package.json
public/javascripts/dialog.js
public/javascripts/main-page-bottom.js
typescript/src/dialog.ts
typescript/src/editGroup.ts
typescript/src/editMyGroups.ts
typescript/src/editUser.ts
typescript/src/index.ts
typescript/src/showApplication.ts
typescript/webpack/webpack.common.js

* Suppression du JS sur la page user
* Extraction des CSS depuis les modules npm

Supprime l’ancien dialog polyfill (pages utilisteur & groupe)

---

app/constants/Constants.scala
app/controllers/Operators.scala
app/controllers/SignupController.scala
app/controllers/UserController.scala
app/models/Authorization.scala
app/models/EventType.scala
app/models/User.scala
app/services/UserService.scala
app/views/editMyGroups.scala.html
app/views/editMyGroupsPage.scala
conf/routes
public/stylesheets/main.css
typescript/src/dialog.ts
typescript/src/editGroup.ts
typescript/src/editMyGroups.ts
typescript/src/editUser.ts

Permet la désactivation à la place du retrait d’un groupe

---

app/views/editGroup.scala.html

Change la couleur du bouton d’édition d’un groupe

---

app/views/editProfile.scala.html

Ajoute un lien vers le groupe depuis le profil

---

app/views/allUsersByGroup.scala.html

Ajoute le lien vers les préinscriptions sur la page utilisateurs classique

---

app/controllers/GroupController.scala
app/controllers/SignupController.scala
app/controllers/UserController.scala
app/models/Application.scala
app/models/Authorization.scala
app/models/UserGroup.scala
app/views/allUsersByGroup.scala.html
app/views/editGroup.scala.html
app/views/editMyGroups.scala.html
app/views/editProfile.scala.html
app/views/helpers/forms.scala
app/views/home/page.scala.html
app/views/main.scala.html
app/views/signupAdmin.scala
build.sbt
project/plugins.sbt

* Change la couleur du bouton d’édition d’un groupe (#1042)
* Ajoute un lien vers le groupe depuis le profil (#1043)
* Ajoute le lien vers les préinscriptions sur la page utilisateurs classique (#1044)
* Supprime le bandeau COVID (#1062)
* Corrige opérateurs invités ne pouvant pas voir les fichiers (#1037)
* Corrige les résultats des préinscriptions passés par cookie (#1046)
* Corrige les groupes non éditables par les responsables (#1045)
* Corrige l’ancien check d’authorization (#1061)
* Mise à jour des dépendances (#1039) (#1034) (#1038) (#1048) (#1047) (#1049) (#1041) (#1053) (#1054) (#1055)

v0.14.4 - Mise en prod 02/06/2021

---

app/views/emails/common.scala

en espérant que ça incite encore plus à ne pas partager ces emails à des non users

Améliore la formulation du footer des emails

---

app/controllers/GroupController.scala
app/views/allUsersByGroup.scala.html
app/views/editGroup.scala.html
app/views/editMyGroups.scala
public/stylesheets/main.css

Améliore la compréhension de la création de compte

---

conf/application.conf

piwik.js fait des POST sur stats.data.gouv.fr

Ajoute stats.data.gouv.fr dans la CSP connect-src

---

app/controllers/ApiController.scala
app/controllers/AreaController.scala
app/controllers/JavascriptController.scala
app/controllers/UserController.scala
app/serializers/ApiModel.scala
app/views/allUsersNew.scala.html
app/views/deploymentDashboard.scala.html
app/views/franceServiceDeploymentDashboard.scala.html
build.sbt
conf/routes
package.json
typescript/src/admin.ts
typescript/src/global.d.ts
typescript/src/index.ts
typescript/src/users.ts
typescript/webpack/webpack.common.js

Corrige aussi la colonne groupes du tableau utilisateurs qui prenait trop de place.

Utilise AJAX pour Tabulator et supprime les scripts inline

---

app/views/emails/welcome.scala.html

ajout paragraphe "comment inviter mes collègues ?" en rapport avec les responsables de groupes

Ajoute paragraphe "comment inviter mes collègues ?"

---

app/models/Application.scala
app/views/showApplication.scala.html

Améliore la visibilité de l’icone demande vue et ajoute la date

---

.github/workflows/test.yml
.scalafmt.conf
app/controllers/ApplicationController.scala
app/serializers/Keys.scala
app/services/UserGroupService.scala
app/services/UserService.scala
app/views/application.scala
app/views/editGroup.scala.html
app/views/editUser.scala.html
app/views/group.scala
app/views/helpers/common.scala
app/views/helpers/head.scala
app/views/showApplication.scala.html
app/views/user.scala
build.sbt
conf/routes
package.json
project/plugins.sbt
typescript/src/editGroup.ts
typescript/src/editMyGroups.ts
typescript/src/editUser.ts
typescript/src/showApplication.ts

* Permet d’entrer un email dans la recherche utilisateur (#1235)
* Change les routes de suppression en POST (#1249)
* Update codacy coverage (#1263)
* Change les GET non nilpotents sur la demande en POST (#1258)
* Lance codacy coverage uniquement s'il y a le token (#1268)
* Mise à jour des dépendances (#1236) (#1225) (#1223) (#1226) (#1230) (#1232) (#1221) (#1238) (#1241) (#1242) (#1243) (#1247) (#1246) (#1245) (#1252) (#1248) (#1254) (#1257) (#1259)

v0.17.1 - Mise en prod 7/12/2021

---

app/controllers/ApplicationController.scala
app/controllers/MandatController.scala

Ajoute `Cache-Control: no-store` sur
* Mes demandes
* CSV mes demandes
* Page d'une demande
* Téléchargement des fichiers
* Page d'un mandat

Ajoute Cache-Control: no-store sur les données personnelles

---

.dockerignore
.scalafmt.conf
app/controllers/ApplicationController.scala
app/controllers/MandatController.scala
build.sbt
conf/evolutions/default/54.sql
develop/aplus/docker-compose.yml
package.json
project/build.properties
project/plugins.sbt

* Clarifie l’utilisation du docker-compose.yml (#1269)
* Ajoute Cache-Control: no-store sur les données personnelles (#1271)
* Supprime la dépendance guava explicite (#1272)
* Ajoute le type de réponse à la vue SQL réponse (#1275)
* Mise à jour des dépendances (#1262) (#1261) (#1264) (#1253) (#1256) (#1260) (#1274) (#1276) (#1277) (#1278)

v0.17.2 - Mise en prod 14/12/2021

---

Dockerfile
app/controllers/ApplicationController.scala
app/models/EventType.scala
app/models/FileMetadata.scala
app/models/dataModels.scala
app/models/formModels.scala
app/services/AttachmentService.scala
app/services/EventService.scala
app/services/FileService.scala
app/services/NotificationService.scala
app/tasks/RemoveExpiredFilesTask.scala
app/tasks/WipeOldDataTask.scala
app/views/application.scala
app/views/createApplication.scala.html
app/views/emails/common.scala
app/views/showApplication.scala.html
build.sbt
conf/application.conf
conf/evolutions/default/55.sql
conf/routes
public/stylesheets/main.css

Il y a pas mal de code pour garder la compatibilité avec le legacy. Il faudra faire un PR de nettoyage.

Passe un antivirus et renomme les fichiers avant sauvegarde

---

.scalafmt.conf
Dockerfile
app/controllers/ApplicationController.scala
app/helper/Time.scala
app/models/EventType.scala
app/models/FileMetadata.scala
app/models/dataModels.scala
app/models/formModels.scala
app/services/AttachmentService.scala
app/services/EventService.scala
app/services/FileService.scala
app/services/NotificationService.scala
app/services/UserService.scala
app/tasks/RemoveExpiredFilesTask.scala
app/tasks/WipeOldDataTask.scala
app/views/application.scala
app/views/createApplication.scala.html
app/views/editGroup.scala.html
app/views/editMyGroups.scala
app/views/emails/common.scala
app/views/showApplication.scala.html
build.sbt
conf/application.conf
conf/evolutions/default/55.sql
conf/routes
public/stylesheets/main.css

Fonctionnalité :
* Passe un antivirus et renomme les fichiers avant sauvegarde (#1319)
* Corrige l’affichage de l’année des janviers shiftée de +1 (#1323)
* Corrige OOM exception et accélère la page mes groupes (#1322)
* Mise à jour des dépendances (#1321) (#1324) (#1329)

v0.18.0 - Mise en prod 23/2/2021

---

app/views/helpers/applications.scala
app/views/myApplications.scala
app/views/myApplications.scala.html
public/stylesheets/main.css

Change le click JS par un lien HTML en background sur les demandes

---

Dockerfile

AdoptOpenJDK est devenu Eclipse Temurin https://adoptium.net/faq.html?variant=openjdk11

Changement des images docker AdoptOpenJDK vers Eclipse Temurin

---

app/models/Application.scala
app/views/helpers/usersInformationsDynamicForm.scala.html
app/views/myApplications.scala

Ajoute des champs optionnels sur la création de demande

---

app/controllers/ApplicationController.scala
app/models/Answer.scala
app/models/Application.scala
app/models/Authorization.scala
app/services/EventService.scala
app/services/FileService.scala
app/tasks/AutoAddExpertTask.scala
app/views/application.scala
conf/routes
test/models/AuthorizationSpec.scala

Suppression du legacy (https://github.com/betagouv/aplus/pull/1319)

Supprime l’ancien téléchargement de fichiers

---

app/controllers/ApiController.scala
app/controllers/AreaController.scala
app/controllers/JavascriptController.scala
app/controllers/MandatController.scala
app/controllers/Operators.scala
app/controllers/UserController.scala
app/models/Error.scala
app/models/EventType.scala
app/models/FranceService.scala
app/serializers/ApiModel.scala
app/serializers/JsonFormats.scala
app/serializers/Keys.scala
app/services/UserGroupService.scala
app/views/franceServiceDeploymentDashboard.scala.html
app/views/franceServices.scala
conf/evolutions/default/57.sql
conf/routes
package.json
typescript/src/franceServices.ts
typescript/src/index.ts

Ajoute les matricules FS

---

app/controllers/ApiController.scala
app/controllers/ApplicationController.scala
app/controllers/CSVImportController.scala
app/controllers/UserController.scala
app/models/UserGroup.scala
app/serializers/ApiModel.scala
app/serializers/UserAndGroupCsvSerializer.scala
app/services/SmsService.scala
app/services/UserGroupService.scala
app/views/allArea.scala.html
app/views/allUsersByGroup.scala.html
app/views/editGroup.scala.html
app/views/helpers/applications.scala
app/views/signup.scala
test/csv/CSVSpec.scala

Supprime la déduction implicite des organismes

---

app/views/welcome.scala.html

Remplace "L’aidant a entamé les démarches habituelles" par "Les démarches habituelles ont déjà été entamées"

Corrige formulation de l'email de bienvenue

---

app/views/emails/notificationBAL.scala.html

Précise qui peut accéder à une demande ou réponse

Précise qui peut accéder à une demande ou réponse

---

app/actions/LoginAction.scala
app/controllers/ApplicationController.scala
app/views/home/page.scala.html
app/views/publicStats.scala
package.json
typescript/webpack/webpack.common.js

Ajoute une page de statistiques publiques

---

app/controllers/LoginController.scala

Ajoute un message d’erreur lorsque l’email de connexion est vide

---

app/controllers/Operators.scala
app/controllers/UserController.scala
app/models/EventType.scala
app/models/User.scala
app/serializers/ApiModel.scala
app/services/UserService.scala
app/views/allUsersByGroup.scala.html
app/views/users.scala
conf/routes
package.json
typescript/src/admin.ts
typescript/src/applicationsAdmin.ts
typescript/src/franceServices.ts
typescript/src/users.ts

Nouvelle page utilisateurs pour tout le monde + bump tabulator 5.5.0

---

.gitignore
start.sh.example
typescript/src/dsfr-fix.css

Fix effets de bords liés au dashboard : 
- icones mauvaise couleur
- ajout du start.sh dans .gitignore et création d'un fichier example

fix dashboard side effects

---

.gitignore
README.md
run.sh.example

Comme promis voici le README.md refait à neuf ! 
J'ai laissé des commandes en commentaire, elles étaient dans le précédent README mais je n'ai pas réussi à les faire fonctionner !
Comme convenu lors de notre visio avec @Alexandre, j'ai modifié la variable d'environnement `DATABASE_URL` et j'ai renommé start.sh.example en run.sh.example. 
Je reste disponible pour plus d'améliorations ✨
J'espère que cette nouvelle doc facilitera les prochain·e·s dev du projet et les personnes qui veulent contribuer pour le plaisir.

Mise à jour du README.md

---

app/controllers/CSVImportController.scala
app/controllers/SignupController.scala
app/controllers/UserController.scala
app/models/Authorization.scala
app/models/User.scala
app/models/dataModels.scala
app/models/formModels.scala
app/serializers/ApiModel.scala
app/services/UserService.scala
app/views/editUser.scala.html
conf/evolutions/default/70.sql
test/browser/AnswerSpec.scala
test/browser/ApplicationAccessSpec.scala
test/browser/ApplicationSpec.scala
test/browser/LoginSpec.scala
typescript/src/users.ts

Ajoute le role de responsable de territoire par organisme

---

app/controllers/ApplicationController.scala
app/views/applications/myApplications.scala
app/views/createApplication.scala
app/views/dashboard.scala
app/views/main.scala
public/stylesheets/aplus-dsfr.css

Liens dépendent des rôles
Le header est responsive
(images de la version précédente du header)

Correction des bugs dans le header et ajout des liens de navigation

---

app/views/errors.scala
app/views/main.scala
app/views/publicStats.scala
public/stylesheets/aplus-dsfr.css

Ajout des mentions obligatoires dans le footer et corrections

---

app/controllers/HomeController.scala
app/views/accessibility.scala
app/views/helpers/common.scala
app/views/home/page.scala.html
app/views/main.scala
app/views/main.scala.html
conf/routes
public/stylesheets/aplus-dsfr.css

Ajoute une page de déclaration d’accessibilité

---

app/controllers/ApplicationController.scala
app/views/application.scala

Améliore le message de création de demande

---

app/controllers/ApplicationController.scala

Ajoute la durée de rétention lors de l’archivage

---

app/modules/AppConfig.scala
app/views/helpers/common.scala
app/views/home/page.scala.html
conf/application.conf

Ajoute un header d’alerte sur la home page

---

app/controllers/ApplicationController.scala
app/views/internalStats.scala
app/views/stats/page.scala.html

Ajoute un filtre réseau sur la page stats

---

app/controllers/ApiController.scala
app/controllers/ApplicationController.scala
app/controllers/AreaController.scala
app/models/Authorization.scala
app/views/franceServiceDeploymentDashboard.scala.html
app/views/helpers/menuNav.scala.html
app/views/publicStats.scala
app/views/stats/page.scala.html
conf/routes

Ajoute une page publique avec le déploiement territorial
